# JetScale Stack Release Configuration
# Reference: https://nightapes.github.io/go-semantic-release/

commitFormat: angular

# Branch Configuration
branch:
  main: release

# Provider Configuration
release: github
github:
  user: "Jetscale-ai"
  repo: "Stack"
  # ✅ Critical: This forces the chart-v tag prefix
  tagPrefix: "chart-v"
