# Go Semantic Release Configuration
# Documentation: https://go-semantic-release.xyz/config

# 1. Commit Analysis
commitFormat: angular

# 2. Provider Configuration
release: github
github:
  # ✅ The Critical Setting
  tagPrefix: "chart-v"
  
  # Optional: Release Assets
  assets:
    - name: "charts/app/*.tgz"
      compress: false
