apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: jetscale-stack

build:
  local:
    push: false
    useDockerCLI: true
    tryImportMissing: true
  artifacts:
    - image: jetscale-backend-local
      context: ../backend
      docker:
        dockerfile: Dockerfile
        target: backend
    - image: jetscale-frontend-local
      context: ../frontend
      docker:
        dockerfile: Dockerfile
        target: frontend

profiles:
  # --------------------------------------------------------
  # LOCAL PROFILE (Kind on laptop) - Keeps local values in chart
  # --------------------------------------------------------
  - name: local-kind
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-stack-test
            chartPath: charts/app
            namespace: jetscale-test-local
            createNamespace: true
            valuesFiles:
              - charts/app/values.local.e2e.yaml

  # --------------------------------------------------------
  # PREVIEW (Updated Path)
  # --------------------------------------------------------
  - name: preview
    deploy:
      helm:
        releases:
          - name: jetscale-stack-preview
            chartPath: charts/app
            createNamespace: true
            # ✅ Point to new location
            valuesFiles:
              - envs/preview/values.yaml

  # --------------------------------------------------------
  # LIVE (Updated Path)
  # --------------------------------------------------------
  - name: live
    deploy:
      helm:
        releases:
          - name: jetscale-stack
            chartPath: charts/app
            createNamespace: true
            # ✅ Point to new location
            valuesFiles:
              - envs/live/values.yaml
