apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: jetscale

# ------------------------------------------------------------------------------
# GLOBAL BUILD: Options Only (No Artifacts)
# ------------------------------------------------------------------------------
build:
  local:
    push: false
    useDockerCLI: true
    tryImportMissing: true
  # ⚠️ CRITICAL: Do not define artifacts here. 
  # They require relative paths (../backend) which do not exist in CI.

profiles:
  # --------------------------------------------------------
  # LOCAL PROFILE (Kind on laptop)
  # --------------------------------------------------------
  - name: local-kind
    build:
      local:
        push: false  # Don't push to registry, load directly to Kind
      artifacts:
        - image: jetscale-backend-local
          context: ../backend
          docker:
            dockerfile: Dockerfile
            target: backend
        - image: jetscale-frontend-local
          context: ../frontend
          docker:
            dockerfile: Dockerfile
            target: frontend
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-test
            chartPath: charts/jetscale
            namespace: jetscale-test-local
            createNamespace: true
            valuesFiles:
              - charts/jetscale/values.local.e2e.yaml

  # --------------------------------------------------------
  # CI PROFILE (Kind on Runner)
  # --------------------------------------------------------
  - name: ci-kind
    # No build section needed.
    # Skaffold will simply deploy the remote images defined in values.yaml.
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-ci
            chartPath: charts/jetscale
            namespace: jetscale-ci
            createNamespace: true
            valuesFiles:
              # Kind CI must be self-contained (no Terraform-managed Secrets/DB/Redis, no ALB)
              - charts/jetscale/values.ci.kind.yaml

  # --------------------------------------------------------
  # CI PROFILE (Kind on laptop - local builds)
  # --------------------------------------------------------
  - name: ci-kind-local
    build:
      local:
        push: false # Don't push to registry, load directly to Kind
      artifacts:
        - image: jetscale-backend-local
          context: ../backend
          docker:
            dockerfile: Dockerfile
            target: backend
        - image: jetscale-frontend-local
          context: ../frontend
          docker:
            dockerfile: Dockerfile
            target: frontend
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-ci
            chartPath: charts/jetscale
            namespace: jetscale-ci
            createNamespace: true
            valuesFiles:
              - charts/jetscale/values.ci.kind.local.yaml

  # --------------------------------------------------------
  # NOTE:
  # Preview + Live EKS deployments are Helm-only (and later ArgoCD), not Skaffold.
  # Skaffold is intentionally scoped to Kind workflows (local + CI) where it shines
  # at building artifacts + deploying ephemeral test stacks.
