apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: jetscale

# ------------------------------------------------------------------------------
# GLOBAL BUILD: Options Only (No Artifacts)
# ------------------------------------------------------------------------------
build:
  local:
    push: false
    useDockerCLI: true
    tryImportMissing: true
    # ⚠️ CRITICAL: Do not define artifacts here.
    # They require relative paths (../backend) which do not exist in CI.

profiles:
  # --------------------------------------------------------
  # LOCAL PROFILE (Kind on laptop)
  # --------------------------------------------------------
  - name: local-kind
    build:
      local:
        # When a ctlptl local registry is configured, Skaffold should push
        # to it so Kind can pull images reliably.
        push: true
      artifacts:
        - image: jetscale-backend-local
          context: ../backend
          docker:
            dockerfile: Dockerfile
            target: backend
            buildArgs:
              GIT_REF_NAME: "{{if .BACKEND_BRANCH}}{{.BACKEND_BRANCH}}{{else}}unknown{{end}}"
              GIT_DESCRIBE: "{{if .BACKEND_VERSION}}{{.BACKEND_VERSION}}{{else}}0.0.0-dev{{end}}"
              GIT_REF: "{{if .BACKEND_GIT_REF}}{{.BACKEND_GIT_REF}}{{else}}unknown{{end}}"
              GIT_SHA: "{{if .BACKEND_GIT_SHA}}{{.BACKEND_GIT_SHA}}{{else}}unknown{{end}}"
              BUILD_TIME: "{{if .BUILD_TIME}}{{.BUILD_TIME}}{{else}}unknown{{end}}"
        - image: jetscale-frontend-local
          context: ../frontend
          docker:
            dockerfile: Dockerfile
            target: frontend
            buildArgs:
              REACT_APP_VERSION: "{{.FRONTEND_VERSION}}"
              REACT_APP_GIT_SHA: "{{.FRONTEND_GIT_SHA}}"
              REACT_APP_BRANCH: "{{.FRONTEND_BRANCH}}"
              REACT_APP_BUILD_TIME: "{{.BUILD_TIME}}"
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-test
            chartPath: charts/jetscale
            namespace: jetscale-test-local
            createNamespace: true
            valuesFiles:
              - charts/jetscale/values.test.yaml
              - charts/jetscale/values.test.local.yaml
            setValueTemplates:
              backend-api.env.JETSCALE_VERSION: "{{if .BACKEND_VERSION}}{{.BACKEND_VERSION}}{{else}}unknown-dev{{end}}"
              backend-api.env.JETSCALE_GIT_SHA: "{{if .BACKEND_GIT_SHA}}{{.BACKEND_GIT_SHA}}{{else}}unknown{{end}}"
              backend-api.env.JETSCALE_GIT_REF: "{{if .BACKEND_GIT_REF}}{{.BACKEND_GIT_REF}}{{else}}unknown{{end}}"
              backend-api.env.JETSCALE_BRANCH: "{{if .BACKEND_BRANCH}}{{.BACKEND_BRANCH}}{{else}}unknown{{end}}"
              backend-api.env.JETSCALE_BUILD_TIME: "{{if .BUILD_TIME}}{{.BUILD_TIME}}{{else}}unknown{{end}}"
              backend-ws.env.JETSCALE_VERSION: "{{if .BACKEND_VERSION}}{{.BACKEND_VERSION}}{{else}}unknown-dev{{end}}"
              backend-ws.env.JETSCALE_GIT_SHA: "{{if .BACKEND_GIT_SHA}}{{.BACKEND_GIT_SHA}}{{else}}unknown{{end}}"
              backend-ws.env.JETSCALE_GIT_REF: "{{if .BACKEND_GIT_REF}}{{.BACKEND_GIT_REF}}{{else}}unknown{{end}}"
              backend-ws.env.JETSCALE_BRANCH: "{{if .BACKEND_BRANCH}}{{.BACKEND_BRANCH}}{{else}}unknown{{end}}"
              backend-ws.env.JETSCALE_BUILD_TIME: "{{if .BUILD_TIME}}{{.BUILD_TIME}}{{else}}unknown{{end}}"

  # --------------------------------------------------------
  # CI PROFILE (Kind on Runner)
  # --------------------------------------------------------
  - name: ci-kind
    # No build section needed.
    # Skaffold will simply deploy the remote images defined in values.test.ci.yaml.
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-ci
            chartPath: charts/jetscale
            namespace: jetscale-ci
            createNamespace: true
            valuesFiles:
              # Kind CI must be self-contained (no Terraform-managed Secrets/DB/Redis, no ALB)
              - charts/jetscale/values.test.yaml
              - charts/jetscale/values.test.ci.yaml
            setValueTemplates:
              backend-api.env.JETSCALE_VERSION: "{{if .BACKEND_VERSION}}{{.BACKEND_VERSION}}{{else}}unknown-dev{{end}}"
              backend-api.env.JETSCALE_GIT_SHA: "{{if .BACKEND_GIT_SHA}}{{.BACKEND_GIT_SHA}}{{else}}unknown{{end}}"
              backend-api.env.JETSCALE_GIT_REF: "{{if .BACKEND_GIT_REF}}{{.BACKEND_GIT_REF}}{{else}}unknown{{end}}"
              backend-api.env.JETSCALE_BRANCH: "{{if .BACKEND_BRANCH}}{{.BACKEND_BRANCH}}{{else}}unknown{{end}}"
              backend-api.env.JETSCALE_BUILD_TIME: "{{if .BUILD_TIME}}{{.BUILD_TIME}}{{else}}unknown{{end}}"
              backend-ws.env.JETSCALE_VERSION: "{{if .BACKEND_VERSION}}{{.BACKEND_VERSION}}{{else}}unknown-dev{{end}}"
              backend-ws.env.JETSCALE_GIT_SHA: "{{if .BACKEND_GIT_SHA}}{{.BACKEND_GIT_SHA}}{{else}}unknown{{end}}"
              backend-ws.env.JETSCALE_GIT_REF: "{{if .BACKEND_GIT_REF}}{{.BACKEND_GIT_REF}}{{else}}unknown{{end}}"
              backend-ws.env.JETSCALE_BRANCH: "{{if .BACKEND_BRANCH}}{{.BACKEND_BRANCH}}{{else}}unknown{{end}}"
              backend-ws.env.JETSCALE_BUILD_TIME: "{{if .BUILD_TIME}}{{.BUILD_TIME}}{{else}}unknown{{end}}"

# --------------------------------------------------------
# NOTE:
# Preview + Live EKS deployments are Helm-only (and later ArgoCD), not Skaffold.
# Skaffold is intentionally scoped to Kind workflows (local + CI) where it shines
# at building artifacts + deploying ephemeral test stacks.
