apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: jetscale-stack

build:
  local:
    push: false
    useDockerCLI: true
    tryImportMissing: true
  artifacts:
    - image: jetscale-backend-local
      context: ../backend
      docker:
        dockerfile: Dockerfile
        target: backend
    - image: jetscale-frontend-local
      context: ../frontend
      docker:
        dockerfile: Dockerfile
        target: frontend

profiles:
  # --------------------------------------------------------
  # LOCAL PROFILE (Kind on laptop)
  # --------------------------------------------------------
  - name: local-kind
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-stack-test
            chartPath: charts/app
            namespace: jetscale-test-local
            createNamespace: true
            valuesFiles:
              - charts/app/values.local.e2e.yaml

  # --------------------------------------------------------
  # CI PROFILE (Restored)
  # --------------------------------------------------------
  - name: ci-kind
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          # Note: Name must match what Magefile expects for Port-Forwarding
          - name: jetscale-stack-ci
            chartPath: charts/app
            # Namespace is overridden by CLI flag in Mage, but good to have default
            namespace: jetscale-ci
            createNamespace: true
            valuesFiles:
              - charts/app/values.local.e2e.yaml

  # --------------------------------------------------------
  # PREVIEW
  # --------------------------------------------------------
  - name: preview
    deploy:
      helm:
        releases:
          - name: jetscale-stack-preview
            chartPath: charts/app
            createNamespace: true
            valuesFiles:
              - envs/preview/values.yaml

  # --------------------------------------------------------
  # LIVE
  # --------------------------------------------------------
  - name: live
    deploy:
      helm:
        releases:
          - name: jetscale-stack
            chartPath: charts/app
            createNamespace: true
            valuesFiles:
              - envs/live/values.yaml
