apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: jetscale-stack

# ------------------------------------------------------------------------------
# GLOBAL BUILD: Default to "Developer Mode" (Build from Source)
# ------------------------------------------------------------------------------
build:
  local:
    push: false
    useDockerCLI: true
    tryImportMissing: true
  artifacts:
    - image: jetscale-backend-local
      context: ../backend
      docker:
        dockerfile: Dockerfile
        target: backend
    - image: jetscale-frontend-local
      context: ../frontend
      docker:
        dockerfile: Dockerfile
        target: frontend

profiles:
  # --------------------------------------------------------
  # LOCAL PROFILE (Kind on laptop)
  # --------------------------------------------------------
  - name: local-kind
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-stack-test
            chartPath: charts/app
            namespace: jetscale-test-local
            createNamespace: true
            valuesFiles:
              - charts/app/values.local.e2e.yaml

  # --------------------------------------------------------
  # CI PROFILE (Kind on Runner)
  # --------------------------------------------------------
  - name: ci-kind
    # 1. DISABLE BUILD: We have no source code in CI
    build:
      artifacts: []
    
    # 2. DEPLOY: Use Preview config (points to GHCR images)
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-stack-ci
            chartPath: charts/app
            namespace: jetscale-ci
            createNamespace: true
            valuesFiles:
              # Uses ghcr.io/jetscale-ai/backend-dev:latest
              - envs/preview/values.yaml

  # --------------------------------------------------------
  # PREVIEW
  # --------------------------------------------------------
  - name: preview
    deploy:
      helm:
        releases:
          - name: jetscale-stack-preview
            chartPath: charts/app
            createNamespace: true
            valuesFiles:
              - envs/preview/values.yaml

  # --------------------------------------------------------
  # LIVE
  # --------------------------------------------------------
  - name: live
    deploy:
      helm:
        releases:
          - name: jetscale-stack
            chartPath: charts/app
            createNamespace: true
            valuesFiles:
              - envs/live/values.yaml
