apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: jetscale-stack

build:
  artifacts:
    # Dev Images (Ubuntu-based, hot reload friendly)
    - image: ghcr.io/jetscale-ai/backend-dev
      context: ../backend
      docker:
        dockerfile: Dockerfile
        target: dev
    - image: ghcr.io/jetscale-ai/frontend-dev
      context: ../frontend
      docker:
        dockerfile: Dockerfile
        target: dev
    # Live Images (Alpine, pinned for releases)
    - image: ghcr.io/jetscale-ai/backend
      context: ../backend
      docker:
        dockerfile: Dockerfile
        target: live
    - image: ghcr.io/jetscale-ai/frontend
      context: ../frontend
      docker:
        dockerfile: Dockerfile
        target: live

profiles:
  # --------------------------------------------------------
  # LOCAL PROFILE (Kind on laptop)
  # --------------------------------------------------------
  - name: local-kind
    deploy:
      helm:
        releases:
          - name: jetscale-stack-local
            chartPath: charts/app
            valuesFiles:
              - charts/app/values.local.yaml

  # --------------------------------------------------------
  # CI PROFILE (Ephemeral Kind)
  # --------------------------------------------------------
  - name: ci-kind
    deploy:
      helm:
        releases:
          - name: jetscale-stack-ci
            chartPath: charts/app
            valuesFiles:
              - charts/app/values.local.yaml # Reuse local dev values as base
            setValues:
              backend-api.devMode.enabled: "false" # STRICTLY disable mounts in CI
              backend-api.service.type: "ClusterIP"
              backend-api.service.nodePort: ""

  # --------------------------------------------------------
  # PREVIEW PROFILE (Ephemeral EKS Namespaces)
  # --------------------------------------------------------
  - name: preview
    deploy:
      helm:
        releases:
          - name: jetscale-stack-preview
            chartPath: charts/app
            valuesFiles:
              - charts/app/values.preview.yaml
            # Dynamic overrides usually passed via CLI flags in CI:
            # --set ingress.host=pr-123.app.jetscale.ai

  # --------------------------------------------------------
  # LIVE PROFILE (Live EKS)
  # --------------------------------------------------------
  - name: live
    deploy:
      helm:
        releases:
          - name: jetscale-stack
            chartPath: charts/app
            valuesFiles:
              - charts/app/values.live.yaml
