apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: jetscale-stack

# ------------------------------------------------------------------------------
# GLOBAL BUILD: Options Only (No Artifacts)
# ------------------------------------------------------------------------------
build:
  local:
    push: false
    useDockerCLI: true
    tryImportMissing: true
  # ⚠️ CRITICAL: Do not define artifacts here. 
  # They require relative paths (../backend) which do not exist in CI.

profiles:
  # --------------------------------------------------------
  # LOCAL PROFILE (Kind on laptop)
  # --------------------------------------------------------
  - name: local-kind
    build:
      artifacts:
        - image: jetscale-backend-local
          context: ../backend
          docker:
            dockerfile: Dockerfile
            target: backend
        - image: jetscale-frontend-local
          context: ../frontend
          docker:
            dockerfile: Dockerfile
            target: frontend
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-stack-test
            chartPath: charts/app
            namespace: jetscale-test-local
            createNamespace: true
            valuesFiles:
              - charts/app/values.local.e2e.yaml

  # --------------------------------------------------------
  # CI PROFILE (Kind on Runner)
  # --------------------------------------------------------
  - name: ci-kind
    # No build section needed. 
    # Skaffold will simply deploy the remote images defined in values.yaml.
    deploy:
      kubeContext: kind-kind
      helm:
        releases:
          - name: jetscale-stack-ci
            chartPath: charts/app
            namespace: jetscale-ci
            createNamespace: true
            valuesFiles:
              # Uses ghcr.io/jetscale-ai/backend-dev:latest
              - envs/preview/values.yaml

  # --------------------------------------------------------
  # PREVIEW
  # --------------------------------------------------------
  - name: preview
    deploy:
      helm:
        releases:
          - name: jetscale-stack-preview
            chartPath: charts/app
            createNamespace: true
            valuesFiles:
              - envs/preview/values.yaml

  # --------------------------------------------------------
  # LIVE
  # --------------------------------------------------------
  - name: live
    deploy:
      helm:
        releases:
          - name: jetscale-stack
            chartPath: charts/app
            createNamespace: true
            valuesFiles:
              - envs/live/values.yaml
